;;-- start emacs server, so emacsclient can connect to it
;;(server-start)

;; package management
;;===================
(require 'package)

(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))

(setq package-enable-at-startup nil)
(package-initialize)

(add-to-list 'load-path "~/dev/emacs/init/lisp")
(add-to-list 'load-path "~/dev/emacs/magit/lisp")
(add-to-list 'custom-theme-load-path "~/dev/emacs/monokai-emacs")

;; basic emacs behaviour
;;======================

;;-- disable backup or place in /tmp directory
;;(setq-default backup-inhibited t)
(setq backup-directory-alist `((".*" . ,temporary-file-directory)))
;;-- disable auto save or place in /tmp directory
;;(setq-default auto-save-default nil)
(setq auto-save-file-name-transforms `((".*" ,temporary-file-directory t)))

;; user interface
;;===============

;;-- custom color themes
(if window-system
    ;; use this theme for the windowed mode
    ;;(load-theme 'solarized-dark t)
    ;;(load-theme 'zenburn t)
    (load-theme 'monokai t)
  ;; use this theme for the nowindow mode (in terminal)
  (load-theme 'monokai t))

(require 'init-evil)
(require 'init-magit)
(require 'init-completion)
(require 'init-search)

(require 'init-indentation)
(require 'init-linenumbers)
(require 'init-statusbar)
(require 'init-windows)

;; programming language modes
;;===========================

;;-- C/C++
(require 'init-c-mode)

;;-- C/C++
(require 'init-perl-mode)

;;-- Fortran
(require 'init-fortran-mode)

;;-- enable CMake
(require 'init-cmake)

;; below is auto-generated by emacs, don't touch!
;;===============================================
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ansi-color-names-vector
   ["#272822" "#F92672" "#A6E22E" "#E6DB74" "#66D9EF" "#FD5FF0" "#A1EFE4" "#F8F8F2"])
 '(compilation-message-face (quote default))
 '(custom-safe-themes
   (quote
    ("949747e29cc4f70866e175218ac41bb1c6a704667ddb31acc035854a74f1add3" "d9046dcd38624dbe0eb84605e77d165e24fdfca3a40c3b13f504728bab0bf99d" default)))
 '(fci-rule-color "#49483E")
 '(highlight-changes-colors ("#FD5FF0" "#AE81FF"))
 '(highlight-tail-colors
   (quote
    (("#49483E" . 0)
     ("#67930F" . 20)
     ("#349B8D" . 30)
     ("#21889B" . 50)
     ("#968B26" . 60)
     ("#A45E0A" . 70)
     ("#A41F99" . 85)
     ("#49483E" . 100))))
 '(magit-diff-use-overlays nil)
 '(magit-use-overlays nil)
 '(vc-annotate-background nil)
 '(vc-annotate-color-map
   (quote
    ((20 . "#F92672")
     (40 . "#CF4F1F")
     (60 . "#C26C0F")
     (80 . "#E6DB74")
     (100 . "#AB8C00")
     (120 . "#A18F00")
     (140 . "#989200")
     (160 . "#8E9500")
     (180 . "#A6E22E")
     (200 . "#729A1E")
     (220 . "#609C3C")
     (240 . "#4E9D5B")
     (260 . "#3C9F79")
     (280 . "#A1EFE4")
     (300 . "#299BA6")
     (320 . "#2896B5")
     (340 . "#2790C3")
     (360 . "#66D9EF"))))
 '(vc-annotate-very-old-color nil)
 '(weechat-color-list
   (unspecified "#272822" "#49483E" "#A20C41" "#F92672" "#67930F" "#A6E22E" "#968B26" "#E6DB74" "#21889B" "#66D9EF" "#A41F99" "#FD5FF0" "#349B8D" "#A1EFE4" "#F8F8F2" "#F8F8F0")))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "Consolas" :foundry "microsoft" :slant normal :weight normal :height 143 :width normal)))))
